### ISSUE TITLE
Awesome completions! 

### ISSUE THREAD

**Issue by idkjs** [LumaKernel/fish-fd-complete#1]
I am here because of the `changed-within` completion.

I want to get the last modified file in current directory and sub-directory.

I cant seem to figure it out. Do you know how that could be done?

Thanks

**Comment by LumaKernel** [comment]
What do you want to complete concretely?
`fd --changed-wihtin {here?}`
I doubt it's domain of this plugin. This simply provides completion information made by `fd --help`.

> I want to get the last modified file in current directory and sub-directory.

It can be done like below.

>find $1 -type f -exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d: -f2- | head
https://stackoverflow.com/a/7448828

or you can do with fd like this.

`fd --exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d: -f2- | head`

**Comment by idkjs** [comment]
`fd --exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d: -f2- | head` doesnt work for me.

This is almost there:
```sh
❯ fd -e re --exec stat | sort -nr | cut -d: -f2- | head -1
06:29 2020" "Aug 10 10:06:29 2020" "Aug 10 10:06:29 2020" "Aug  9 18:12:28 2020" 4096 8 0 src/Router.re
```

This line returns the file that was last modified. I now need it to return only the file path, the `src/Router`

**Comment by LumaKernel** [comment]
If you want to do something with fd, I recommend you should ask it to [fd](https://github.com/sharkdp/fd) community. I have nothing to do with that. This repository is just completion plugin. Sorry.

**Comment by idkjs** [comment]
Already done. Thanks for the feedback.

**Comment by idkjs** [comment]
https://github.com/sharkdp/fd/issues/640#issuecomment-674443492
